version: "3.9"
services:
  postgres:
    image: postgres:18-alpine@sha256:035b9ab53cfa147d7202b61f5f7782b939ae815b7d6bc81c96b7b42ff1fca950
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: social-income
      POSTGRES_PASSWORD: social-income
      POSTGRES_DB: social-income
      TZ: "Europe/Zurich"
      PGTZ: "Europe/Zurich"

  mockserver:
    image: smartive/mockserver:v2.18.2@sha256:072af1580dc44bf28730702f813eef0e142d595de9e48ccba4245343b0fd191c
    ports:
      - "1080:1080"
