name: Backend Functions - PR Run
on:
  pull_request:
    paths:
      - "backend/**"
      - "shared/**"
jobs:
  test:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install & Setup Firebase Emulator Suite
        working-directory: backend
        run: |
          npm -g install firebase-tools && \
          firebase setup:emulators:firestore && \
          firebase setup:emulators:ui

      - name: Install Dependencies
        run: npm --workspace=@socialincome/backend install

      - name: Run Tests
        working-directory: backend/functions
        run: npm run backend:test
